# Generated by Django 4.2.7 on 2023-11-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birth_date',
            new_name='born_date',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='birth_place',
            new_name='born_location',
        ),
    ]
