# Generated by Django 4.2.7 on 2023-12-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_birth_date_author_born_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
